# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area1', models.CharField(choices=[('Mumbai Central', 'Mumbai Central'), ('Goregaon', 'Goregaon'), ('TRU', 'trucks'), ('WRI', 'writing')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas1', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.IntegerField()),
                ('user_write', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('type', models.CharField(default='normal', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('heading', models.CharField(default='No Heading', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='photo1')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.form2')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Likes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('type', models.CharField(default='normal', max_length=10)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Discussion')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localities1', models.CharField(max_length=60)),
                ('areas2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Areas')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality1', models.CharField(max_length=50)),
                ('area2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('user_write', models.CharField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
                ('urls1', models.CharField(default='/login/home/Railway/', max_length=1000)),
                ('type', models.CharField(default='normal', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificLocality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('heading', models.CharField(default='No Heading', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Areas')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Localities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_problem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='photo/765-default-avatar.png', upload_to='photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='likes1',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.SpecificLocality'),
        ),
        migrations.AddField(
            model_name='likes1',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form2',
            name='genproblems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.GeneralProblems'),
        ),
        migrations.AddField(
            model_name='form2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
