# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificlocality',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Area'),
        ),
        migrations.AlterField(
            model_name='specificlocality',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Locality'),
        ),
    ]
