# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20161003_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificlocality',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Areas'),
        ),
        migrations.AlterField(
            model_name='specificlocality',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Localities'),
        ),
    ]
